version: '3.5'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

#  composerupdator:
#    container_name: composerupdator
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: 'no'
#    command: 'composer install'
#    volumes:
#      - ./www:/var/www

  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www

  postgresql:
    container_name: postgresql
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./postgresql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=otus
      - POSTGRES_DB=otus
volumes:
  postgresql:
#
#
#  app:
#    container_name: app
#    build:
#      context: ../base/php
#    volumes:
#      - ./www:/var/www
#    depends_on:
#      - postgresql
#    links:
#      - postgresql
#
#  migrator:
#    container_name: migrator
#    build:
#      context: ../base/php
#    restart: 'no'
#    command: bash -c 'sleep 60; php /var/www/artisan migrate'
#    links:
#      - app
#      - postgresql
#    depends_on:
#      - postgresql
#    volumes:
#      - ./www:/var/www
